### ISSUE TITLE
module-level incompatibility

### ISSUE THREAD

**Issue by brainysmurf** [mzagorny/gas-local#3]
Both case 1 and case 2 work in GAS context, but not in node.js with gas-local:

Case 1:
```js
// app.gs --------
function initApp(options) {
  initLibraries(); 
}
initApp(); // <-- called here, "not defined" error in node.js

// libraries.gs --------
function initLibraries() {
   Logger.log("inited");
}
```

Case 2:
```js
// app.gs --------
function initApp(options) {
  initLibraries(); 
}

// libraries.gs --------
function initLibraries() {
  Logger.log("inited");
}
initApp();  // <-- called here, both contexts no error
```

For case 1 with node.js, you end up with "initLibraries is not defined". However, this is perfectly fine in GAS.

Please advise if this is, as I expect, an unresolvable incompatibility (due to collisions with the global context) or is there perhaps something that can be resolved cleanly?

**Comment by mzagorny** [comment]
Hi @brainysmurf, sorry for late answer and thanks for first issue reporting :) Just fore sure -  are the app.gs and libraries.gs in same GAS module?

**Comment by brainysmurf** [comment]
They are different "files" in the front-end on Google, created via New->Script, and different files on disk in the local stack. Those therefore are different "modules"... or am I mixing up the terminology?

In any case, Case 1 can be mitigated by putting the `initApp()` in the "libraries" file, at the end, or in a file that comes alphabetically after "libraries".

So I'm thinking it has to do with the context being created, for the vm, in which files are read in alphabetically and variables are available one file at a time. Google must be doing something more complex than that.

**Comment by mzagorny** [comment]
ah, now understand :) Thanks for explanation! 
Yes, you are right - order of loading matters. node vm executes function's call on file load (in this case initApp) and if file with the implementation was not loaded yet, then it will be error as you described. 
So this is unresolvable incompatibility in current implementation, indeed. 
Maybe vm have options for deferred function call?

**Comment by brainysmurf** [comment]
If that's the case then we have two different run-times with an important caveat. Or is there a way to simulate — with the node stack — Google's way of deferring execution of top-level code until all functions in all the files have been loaded? I'm no vm expert, but at least we understand what we are looking for.

**Comment by mzagorny** [comment]
Yes, this is the difference. 
i have one idea here: what if combine all files into one before load somehow? In other hand this looks too complicated. 
if you will solve this, then pull request will be very welcome. i close the issue for now. 
Appreciate for your contribution to my humble project 👍

**Comment by brainysmurf** [comment]
I found a repo that hoists function declarations; we can probably use that. I'll send a pull request whenever I get around to it.
https://www.npmjs.com/package/hoister
