### ISSUE TITLE
Filter AppleDouble files

### ISSUE THREAD

**Issue by ina6ra** [mzagorny/gas-local#7]
I'm using a Macintosh.
By editing the file according to the Mac specification, ._ AppleDouble is created.
I want to ignore this files. Please tell me how to do it.

**Comment by mzagorny** [comment]
Hi @ina6ra , sorry for very late response! Please have a look at pull request #4 by @brainysmurf , he have addressed exactly what you are asking :)

**Comment by ina6ra** [comment]
@mzagorny @brainysmurf 
Great Thanks!

With reference to #4 , the following code seems to solve it.

```
var path = require('path');
var ctx = gas.require('./src', {}, {
  filter: function(f) {
    var ext = path.extname(f);
    var base = path.basename(f);
    if(base.match(/^\._/) != null) return false;
    return ext == '.js';
  }
});
```

**Comment by mzagorny** [comment]
Nice to hear that and thanks for using my module :)
