### ISSUE TITLE
Provide instructions on how to 'Develop and test your google apps script project locally'

### ISSUE THREAD

**Issue by dam0** [mzagorny/gas-local#9]
Please elaborate on how to setup and run a project using gas-local..

**Comment by mzagorny** [comment]
Hi @dam0 Damian, what's the issue? Have you tried as it described in Workflow section?

**Comment by dam0** [comment]
When calling my function 'glib.develop()', returns the error 'ReferenceError: SpreadsheetApp is not defined'.

So I was hoping for a sample app or a bit of guidance on how to setup node for testing locally?

**Comment by mzagorny** [comment]
Ah, understand you now. This is expected error. gas-local provides ability to execute gas-scripts from runtime perspective. But it doesn't provide emulation/default mocks for google services. Only Logger and Utility classes mocks comes ot-of the-box. You should mock any other google classes by yourself. See https://github.com/mzagorny/gas-local#how-to-mock-google-services
